const ORIENTATION_UP = "up";
const ORIENTATION_DOWN = "down";
const ORIENTATION_LEFT = "left";
const ORIENTATION_RIGHT = "right";
const ORIENTATION_DEFAULT = ORIENTATION_UP;

const IMAGE_PLANE_SIZE = 40;
const PLANE_SPEED = 10;

const MY_PLANE_COLOR = "red";
const MY_PLANE_HP = 100;

const ENEMY_COLOR = "yellow";
const ENEMY_HP = 50;
let ENEMY_SPEED=5;

const BULLET_DEFAULT_RADIUS = 2;
const BULLET_DEFAULT_SPEED = 20;
const BULLET_DEFAULT_DAMAGE = 30;
const BULLET_DEFAULT_COLOR = "red";

const SCORE_DEFAULT_COLOR = "red";
const FONT = "bold 20px verdana, sans-serif";

const REVERSE = -1;
const NONREVERSE = 1;

let TIME_SETINTERVAL_DEFAULT = 100;

let dataPlanes = [[200, 200, PLANE_SPEED, MY_PLANE_HP, MY_PLANE_COLOR],
    [0, 100, ENEMY_SPEED, ENEMY_HP, ENEMY_COLOR],
    [100, canvas.height-IMAGE_PLANE_SIZE, ENEMY_SPEED, ENEMY_HP, ENEMY_COLOR],
    [canvas.width-IMAGE_PLANE_SIZE, 400, ENEMY_SPEED, ENEMY_HP, ENEMY_COLOR],
    [400, 0, ENEMY_SPEED, ENEMY_HP, ENEMY_COLOR],
    [30, 60, ENEMY_SPEED, ENEMY_HP, ENEMY_COLOR],
    [50, canvas.height-IMAGE_PLANE_SIZE-30, ENEMY_SPEED, ENEMY_HP, ENEMY_COLOR],
    [canvas.width-IMAGE_PLANE_SIZE -50, 150, ENEMY_SPEED, ENEMY_HP, ENEMY_COLOR],
    [100, 0, ENEMY_SPEED, ENEMY_HP, ENEMY_COLOR]
];
